spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quest_review
    username: root
    password: dbWorkDigited1
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update