spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quest_review
    username: root
    password: Francesco2011
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create